### PR TITLE
feat: add midi

### PR DESCRIPTION
**Pull request by johnhooks**
I've been having a lot of fun with this. I just wanted to share some work I did to it.

I restructured everything so I could use TypeScript, and it's pretty half baked. But I really though the Patch Bank need to be MIDI controlled 😄.

I wanted to know if you though any of this looked interesting. I need to read through your code more to know how to integrate the MIDI controller. But it's kinda working right now. Check it out at https://johnhooks.io/plaits-editor/patch_bank.html

The majority of the source I added is in the `src` directory. I added an `update` method to `PatchBankApp` so it could be called `onmidimessage`. The gate is not being controlled right and I have an error coming up:

```
Uncaught TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite.
```

I must not be providing the right values to the synth. 

I'm planning on moving the code into TypeScript, also I'm thinking of using SvelteKit to simplify the structure of the UI.

Thanks for open sourcing this!

### CODE REVIEW

**Comment by johnhooks** [comment]
Also, just to make sure you know, I'm not suggesting all these changes, I just wanted to share and ask for some advice on what kinda of arguments I should be feeding to the synth and advice on how to fix the gate.

The tooling I added for auto formatting modified a lot of code, if your not interested in all that but would like the MIDI code, I can rewrite it in regular JavaScript.

**Comment by pichenettes** [comment]
Gate is a float, should go to 1.0 when a note on is received, and go to 0.0 when a note down is received. "The provided float value is non-finite." makes me think it's not 0.0 or 1.0 but you did some calculation that possibly overflowed or led to a division by 0.

**Comment by johnhooks** [comment]
Thanks for the info, I'll make sure I'm passing in an appropriate value. I also probably need to read up more on MIDI messages. My attempt to parse them is probably pretty naive.

Edit: This currently just passes all midi data as though it is a note on message, which is totally wrong. Reading up on parsing midi.

Another feature I'm going to add is saving the patch bank to IndexedDB so it doesn't disappear ever page reload.

**Comment by johnhooks** [comment]
It's working now. The only MIDI messages it is using is note on and off. Also I changed patch select to a click event. If there isn't a MIDI device it will play the patch, but if there is it will just select the patch, not play it.
https://johnhooks.io/plaits-editor/patch_bank.html

**Comment by johnhooks** [comment]
I moved it all to the same style and it's working correctly.

I added a `package.json` and `jsconfig.json` so I could use the `@types/webmidi` package and provide all the correct types in the JSDocs.

**Comment by johnhooks** [comment]
Closing, work will continue at https://github.com/johnhooks/plaits-editor.

**Pull request closed without merging**
